name: Build 4Combat Installer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar pacotes
        run: dotnet restore CombatScore.UI/CombatScore.UI.csproj

      - name: Publicar aplicação
        run: dotnet publish CombatScore.UI/CombatScore.UI.csproj -c Release -r win-x64 --self-contained true -o publish

      - name: Instalar Inno Setup
        run: choco install innosetup -y

      - name: Gerar instalador
        run: iscc 4CombatSetup.iss

      - name: Enviar instalador
        uses: actions/upload-artifact@v4
        with:
          name: 4CombatSetup
          path: installer-output/4CombatSetup.exe